(in-package #:tempus.tests)

(defsuite (tempus.comm :in test))
(in-suite tempus.comm)

(deftest say ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player)
                  (eva mock-player))
    (tempus::interpret-command alice "say foo bar")
    (char-output-is alice "&BYou say, &c'foo bar'&n~%")
    (char-output-is bob "&BAlice says, &c'foo bar'&n~%")
    (char-output-is eva "&BAlice says, &c'foo bar'&n~%")
    (clear-mock-buffers alice bob eva)

    (tempus::interpret-command alice "'foo bar")
    (char-output-is alice "&BYou say, &c'foo bar'&n~%")
    (char-output-is bob "&BAlice says, &c'foo bar'&n~%")
    (char-output-is eva "&BAlice says, &c'foo bar'&n~%")
    (clear-mock-buffers alice bob eva)

    (tempus::interpret-command alice "' foo bar")
    (char-output-is alice "&BYou say, &c'foo bar'&n~%")
    (char-output-is bob "&BAlice says, &c'foo bar'&n~%")
    (char-output-is eva "&BAlice says, &c'foo bar'&n~%")))

(deftest say-with-escapes ()
  (with-fixtures ((alice mock-player))
    (tempus::interpret-command alice "' $ is a dollar sign")
    (char-output-is alice "&BYou say, &c'$ is a dollar sign'&n~%")
    (clear-mock-buffers alice)
    (tempus::interpret-command alice "' & is an ampersand")
    (char-output-is alice "&BYou say, &c'&& is an ampersand'&n~%")
    (clear-mock-buffers alice)
    (tempus::interpret-command alice "' \\ is a backslash")
    (char-output-is alice "&BYou say, &c'\\ is a backslash'&n~%")
    (clear-mock-buffers alice)
    (tempus::interpret-command alice "' ] is a right bracket")
    (char-output-is alice "&BYou say, &c'] is a right bracket'&n~%")))

(deftest sayto ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player)
                  (eva mock-player))
    (clear-mock-buffers alice bob eva)
    (tempus::interpret-command alice ">bob foo bar")
    (char-output-is alice "&BYou say to Bob, &c'foo bar'&n~%")
    (char-output-is bob "&BAlice says to you, &c'foo bar'&n~%")
    (char-output-is eva "&BAlice says to Bob, &c'foo bar'&n~%")
    (clear-mock-buffers alice bob eva)))

(deftest gossip ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player))
    (setf (tempus::level-of alice) 10)
    (tempus::interpret-command alice "gossip I did it my way")
    (char-output-is alice "&gYou gossip, &n'I did it my way'~%")
    (char-output-is bob "&gAlice gossips, &n'I did it my way'~%")

    (clear-mock-buffers alice bob)
    (tempus::interpret-command alice "gossip")
    (is (equal "Yes, gossip, fine, gossip we must, but WHAT???~%"
               (char-output alice)))
    (char-output-is bob "")))

(deftest tell ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player))
    (tempus::interpret-command alice "tell bob hello")
    (char-output-is alice "&rYou tell Bob,&n 'hello'~%")
    (char-output-is bob "&rAlice tells you,&n 'hello'~%")))

(deftest retell ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player))
    (tempus::interpret-command alice "tell bob hello")
    (clear-mock-buffers alice bob)
    (tempus::interpret-command alice "retell again")
    (char-output-is alice "&rYou tell Bob,&n 'again'~%")
    (char-output-is bob "&rAlice tells you,&n 'again'~%")))

(deftest reply ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player))
    (tempus::interpret-command alice "tell bob hello")
    (clear-mock-buffers alice bob)
    (tempus::interpret-command bob "reply hi there")
    (char-output-is alice "&rBob tells you,&n 'hi there'~%")
    (char-output-is bob "&rYou tell Alice,&n 'hi there'~%")))

(deftest whisper ()
  (with-fixtures ((alice mock-player)
                  (bob mock-player)
                  (eva mock-player))
    (tempus::interpret-command alice "whisper bob hello")
    (char-output-is alice "&yYou whisper to Bob,&n 'hello'~%")
    (char-output-is bob "&yAlice whispers to you,&n 'hello'~%")
    (char-output-is eva "Alice whispers something to Bob.~%")))