(in-package :tempus)

;;; Room search commands
(defparameter +search-com-none+ 0)
(defparameter +search-com-door+ 1)
(defparameter +search-com-mobile+ 2)
(defparameter +search-com-object+ 3)
(defparameter +search-com-remove+ 4)
(defparameter +search-com-give+ 5)
(defparameter +search-com-equip+ 6)
(defparameter +search-com-transport+ 7)
(defparameter +search-com-spell+ 8)
(defparameter +search-com-damage+ 9)
(defparameter +search-com-spawn+ 10)
(defparameter +search-com-loadroom+ 11)
(defparameter +num-search-com+ 12)

;;; Room search flags
(defparameter +search-repeatable+ (ash 1 0))
(defparameter +search-tripped+ (ash 1 1))
(defparameter +search-ignore+ (ash 1 2))
(defparameter +search-clanpasswd+ (ash 1 3))
(defparameter +search-trig-enter+ (ash 1 4))
(defparameter +search-trig-fall+ (ash 1 5)) ; triggers when a player falls into the room (e.g. a spike pit)
(defparameter +search-notrig-fly+ (ash 1 6))
(defparameter +search-nomob+ (ash 1 7))
(defparameter +search-newbie-only+ (ash 1 8))
(defparameter +search-nomessage+ (ash 1 9))
(defparameter +search-noevil+ (ash 1 10))
(defparameter +search-noneutral+ (ash 1 11))
(defparameter +search-nogood+ (ash 1 12))
(defparameter +search-nomage+ (ash 1 13))
(defparameter +search-nocleric+ (ash 1 14))
(defparameter +search-nothief+ (ash 1 15))
(defparameter +search-nobarb+ (ash 1 16))
(defparameter +search-noranger+ (ash 1 17))
(defparameter +search-noknight+ (ash 1 18))
(defparameter +search-nomonk+ (ash 1 19))
(defparameter +search-nopsionic+ (ash 1 20))
(defparameter +search-nophysic+ (ash 1 21))
(defparameter +search-nomerc+ (ash 1 22))
(defparameter +search-nobard+ (ash 1 23))
(defparameter +search-noabbrev+ (ash 1 24))
(defparameter +search-noaffmob+ (ash 1 25))
(defparameter +search-noplayer+ (ash 1 26))
(defparameter +search-remort-only+ (ash 1 27))
(defparameter +search-match-all+ (ash 1 28))
(defparameter +search-no-look+ (ash 1 29))
(defparameter +search-fail-trip+ (ash 1 30))

(defparameter +num-search-bits+ 31)

(defclass special-search-data ()
  ((command-keys :accessor command-keys-of :initarg :command-keys :initform nil)
   (keywords :accessor keywords-of :initarg :keywords :initform nil)
   (to-vict :accessor to-vict-of :initarg :to-vict :initform nil)
   (to-room :accessor to-room-of :initarg :to-room :initform nil)
   (to-remote :accessor to-remote-of :initarg :to-remote :initform nil)
   (command :accessor command-of :initarg :command :initform nil)
   (flags :accessor flags-of :initarg :flags :initform nil)
   (arg :accessor arg-of :initarg :args :initform (make-array 3))
   (fail-chance :accessor fail-chance-of :initarg :fail-chance :initform nil)))
