(in-package :tempus)

(defclass special-search-data ()
  ((trigger :accessor trigger-of :initarg :trigger)
   (keywords :accessor keywords-of :initarg :keywords)
   (to-vict :accessor to-vict-of :initarg :to-vict :initform nil)
   (to-room :accessor to-room-of :initarg :to-room :initform nil)
   (to-remote :accessor to-remote-of :initarg :to-remote :initform nil)
   (command :accessor command-of :initarg :command :initform 0)
   (flags :accessor flags-of :initarg :flags :initform 0)
   (arg :accessor arg-of :initarg :args :initform (make-array 3 :initial-element -1))
   (fail-chance :accessor fail-chance-of :initarg :fail-chance :initform 0)))
